[package]
name = "sadri"
version = "0.1.0"
authors = ["Ali Sadri <ali.sadri.1993@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
